name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Windows
        uses: love-actions/love-actions-windows@v1
        with:
          game_name: break-tetris
          version: 11.3

      - name: Build MacOS (Portable)
        uses: love-actions/love-actions-macos-portable@v1
        with:
          game_name: break-tetris
          version: 11.3

      - name: Build Linux (AppImage)
        uses: love-actions/love-actions-linux@v1
        with:
          game_name: break-tetris
          version: 11.3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/*.zip
            build/macos-portable/*.zip
            build/linux/*.AppImage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
